spring:
  profiles:
    active: dev
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/portal?verifyServerCertificate=false&useSSL=true&createDatabaseIfNotExist=true
    username: root
    password: 123
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false


---

spring:
  profiles: container
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?verifyServerCertificate=false&useSSL=true&createDatabaseIfNotExist=true
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
